export enum CategoryEnum{
  PASSEIO = 'PASSEIO',
  MOTO = 'MOTO',
  CAMINHONETE = 'CAMINHONETE',
  UTILITARIO = 'UTILITÁRIO',
  SUV = 'SUV',
  VAN = 'VAN',
  ONIBUS = 'ÔNIBUS',
  CAMINHAO = 'CAMINHÃO',
  PCD = 'PCD'
}